import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { Navbar, Footer } from "@/components"

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Car Catalog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      {/* <body className={inter.className}> */}
      <body className="realtive">
      <Navbar />
        {children}
      <Footer />
      </body>
    </html>
  )
}
